dist: bionic
language: node_js
node_js:
  - 10
services:
  - docker
before_install:
  # ensure usage of Node.js LTS
  - nvm install 10
  - nvm use 10
  - node --version

  # start ganache snapshot
  - docker run -d --rm -p 8545:8545 gcr.io/zaidan-eth-net/0x-snapshot:latest
install:
  - yarn
  - yarn build
script:
  - yarn test:ci